language: python
sudo: false
python: 3.5
cache:
  - pip: true
addons:
  apt:
    packages:
    - swig
    - libxml2-dev
    - libglpk-dev
    - glpk-utils
env:
  - DEPLOY_BRANCH="gh-pages"

before_install:
# travis_retry may overcome some poor network conditions
  - travis_retry pip install -U pip setuptools wheel
install:
  - travis_retry pip install -U -r requirements.in

# as set up in 'memote.ini' this will create a JSON file in Results
script: memote

# automatic deploys to 'gh-pages' only happen on commits not PRs to 'master'
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
    condition: "${TRAVIS_REPO_SLUG}" == ""
